### ISSUE TITLE
Two small bugs to report

### ISSUE THREAD

**Issue by TheRealDxRed** [thepaperpilot/Babble-Buds#28]
First, when opening the popout stage, characters do not render.
Second, the bouncing animation plays only once after _releasing_ the up arrow key.

Figured I'd report these as I've not seen anyone else. All of these bugs were found on the latest win32 x86 release.

**Comment by thepaperpilot** [comment]
The popout now works in the most recent release (0.9.99-weekly.1). The second bug sounds like intended behavior - the bouncing animation won't queue up or anything.
